version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://murilorsimoes:ZNwsKiPg7KFYZOJd@desafioapibasica.f36dn.mongodb.net/?retryWrites=true&w=majority&appName=DesafioApiBasica
    command: npm run dev

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
